### ISSUE TITLE
Data Class

### ISSUE THREAD

**Issue by MauricioOrtiz1999** [TMachon/ProjetPoo3A#6]
Hello, my name is Mauricio Ortiz and I am a student. I saw your code and you may have a code smell, Data class, because you have some classes that just store information and have no other functionality within the project. To refactor that code smell, you can add methods to those classes. Besides this, you can change the accessibility in the fields of those classes to improve your code.

**Comment by TMachon** [comment]
Hi Mauricio, and Joan, and Edwin. I'm pleased to see that this old repo of mine is used as an assignment by other CS students, but as you can image, this project has not been supported for a long time. In fact, it also was a school assignment, so we didn't bother to maintain it after we turned it in. If you want to work on the code further, feel free to fork this repo and work on the fork instead of creating issues here, as I said this is a dead project and we won't be maintaining it anymore.
